### ISSUE TITLE
列数可以动态设置吗

### ISSUE THREAD

**Issue by AndMy** [zfman/TimetableView#22]
列不确定，如何实现下图功能

![11](https://user-images.githubusercontent.com/7222340/47644910-69c15000-dbaa-11e8-8f21-452c2569f34b.png)

**Comment by zfman** [comment]
@AndMy 抱歉刚看到消息，艾特我一下我才会收到通知的哟。

7列之内是可以控制显示某列的，并且可以设置隐藏周末，不知道你的列的范围是什么？

**Comment by zfman** [comment]
@AndMy 你也可以把你的需求说一下，说不定下个版本就有了呢，近期正有更新的计划

**Comment by panyancen** [comment]
想要以module加入我的项目，好按公司的需求改代码，但是那样加入会报错，以这种implementation 'com.zhuangfei:TimetableView:2.0.6'方式不报错，你可以提供正确的包吗？或者指点。报错的内容：java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference
                                                                      at com.zhuangfei.timetable.operater.SimpleOperater.initPanel(SimpleOperater.java:323)
                                                                      at com.zhuangfei.timetable.operater.SimpleOperater.replaceScrollView(SimpleOperater.java:358)
                                                                      at com.zhuangfei.timetable.operater.SimpleOperater.showView(SimpleOperater.java:412)
                                                                      at com.zhuangfei.timetable.TimetableView.showView(TimetableView.java:875)
                                                                      at com.canruo.hexin.module.classcard.fragment.ClassScheduleCardFragment.initTimetableView(ClassScheduleCardFragment.java:227)
                                                                      at com.canruo.hexin.module.classcard.fragment.ClassScheduleCardFragment.finishCreateView(ClassScheduleCardFragment.java:77)
                                                                      at com.canruo.hexin.base.RxLazyFragment.onViewCreated(RxLazyFragment.java:50) @zfman

**Comment by panyancen** [comment]
不是的，有两种依赖方式，第一种方法直接;implementation 'com.zhuangfei:TimetableView:2.0.6', 第二种依赖方式，把你的包以module的方式放在项目，implementation project(':TimetableView')的方式。我没有改变任何代码，只改变依赖方式，第一种可以，第二种不行

**Comment by panyancen** [comment]
@zfman

**Comment by zfman** [comment]
@panyancen 好的，我晚上试试，看看是不是那个module有问题

**Comment by panyancen** [comment]
好的，谢谢 @zfman

**Comment by zfman** [comment]
@panyancen 抱歉，昨天晚上有其他事情耽误了，所以我昨天晚上只是大概试了一下，貌似确实有点问题，没有报错，就是找不到TimetableView类。你要实现什么需求，大部分的需求都可以模仿SimpleOperator来实现，可以加我qq:1193600556，这上边交流效率比较低
